repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --no-update --since-commit HEAD --fail'
        language: system
        stages: ["commit", "push"]
