#!/usr/bin/env sh

if [ -z "$2" ]; then
	DIR="$1"
else
	DIR="$2"
fi

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	printf "%s" "$DIR" | tr -d '\n' | setsid -f wl-copy
else
	printf "%s" "$DIR" | tr -d '\n' | setsid -f xclip -i -selection clipboard
fi
