#!/usr/bin/env sh

. "$(dirname "$0")"/.nnn-plugin-helper
export CUR_CTX=1

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	DIR=$(wl-paste)
else
	DIR=$(xclip -o -selection clipboard)
fi

nnn_cd "${DIR}"
