#!/bin/bash

# Description: Workaround to open files, determined by $MIMETYPE as not 'text/*', in neovim in current terminal

set -euf -o noclobber -o noglob -o nounset
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n

FILE_PATH="$1"
MIMETYPE="$( file -bL --mime-type -- "${FILE_PATH}" )"

open_neovim () {
	local size
	size=$(wc -c < "${FILE_PATH}")
	# do not apply nvim plugins to file > 1MB
	if (( size > 1000000 )); then
		nvim -u NONE "${FILE_PATH}"
	else
		nvim "${FILE_PATH}"
	fi
}

handle_text() {
	mimetype="${1}"
	case "${mimetype}" in
		# application/vnd.hp-HPGL = Makefile
		text/* | application/vnd.hp-HPGL | application/json | application/x-ndjson | application/javascript)
			open_neovim
		exit 0;;
	esac
}

handle_blocked() {
	case "${MIMETYPE}" in
		application/x-sharedlib | application/x-shared-library-la | application/x-executable | application/x-pie-executable | application/octet-stream)
			if ! which xxxd > /dev/null 2>&1; then
				xxd -d -u -g 1 -c 8 "${FILE_PATH}" 2>/dev/null | less
			else
				>&2 echo "xxd is missing"
			fi
			exit 0
	esac
}

handle_fallback() {
	if type xdg-open >/dev/null 2>&1; then
		nohup xdg-open "${FILE_PATH}" >/dev/null 2>&1 &
		exit 0
	fi
}

handle_text "${MIMETYPE}"
handle_blocked "${MIMETYPE}"
handle_fallback

echo "ERROR: Reached end of nnn_my_opener" >&2
exit 1
