# yazi file manager configuration
# https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
# Layout ratio: parent, current, preview
ratio = [1, 2, 2]

# Sort by modification time
sort_by = "mtime"
sort_sensitive = false
sort_reverse = true
sort_dir_first = true

# Show hidden files
show_hidden = true
show_symlink = true

# Display file size on the right side of the file list row
linemode = "size"

# Number of files to keep above and below the cursor when moving through the file list
scrolloff = 0

# Shown inside zellij pane frames
title_format = "File manager"

[opener]
hexyl = [
	{ run = 'hexyl "$@" | less -R', block = true, desc = "Hex view" },
]

[open]
# Open in CLI by default
# 'Tab' key = show file mimetype seen by yazi ('c' key to copy file type field)
prepend_rules = [
	{ url = "*.service", use = "edit" },
	{ url = "*.conf", use = "edit" },
	{ url = "*.ini",  use = "edit" },
	{ mime = "application/wine-extension-ini", use = "edit" },
	{ mime = "application/octet-stream", use = "hexyl" },
]

[plugin]
# https://github.com/yazi-rs/plugins/tree/main/piper.yazi
prepend_previewers = [
	{ url = "*.csv", run = 'piper -- column -ts, "$1"' },
	{ url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
	{ url = "*/", run = 'piper -- eza --all -TL=3 -I .git --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]
# https://github.com/yazi-rs/plugins/tree/main/git.yazi
[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"
[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"